### ISSUE TITLE
Use Job instead of Thread

### ISSUE THREAD

**Issue by nallath** [kartchnb/AutoTowersGenerator#1]
In this part of the plugin you spawn your own thread (https://github.com/kartchnb/AutoTowersGenerator/blob/cea2bb4f728350a6d4d04e64c2932ef24175f0d2/AutoTowersGenerator.py#L268-L283) that waits for the process of creating a temp tower to be completed.

In Uranium there is already a convenience class that handles all of this for you (https://github.com/Ultimaker/Uranium/blob/master/UM/Job.py). There are a few examples that show how to use jobs in various plugins. I use them in my own plugins as well; https://github.com/nallath/CuraOrientationPlugin/blob/master/CalculateOrientationJob.py

Your current solution is fine ofc, but you can save yourself some headaches by re-using what is already there :)

**Comment by kartchnb** [comment]
Thank you for letting me know about the Job class!  Super-useful.  I've made that change in v1.0.3.  Although it could probably use improvement, it works on my end.

I appreciate you taking the time to test my plugin and educating me a bit!
