### ISSUE TITLE
Update OpenSCAD logic on Windows to look at `%PATH%`

### ISSUE THREAD

**Issue by kleinwareio** [kartchnb/AutoTowersGenerator#100]
Currently the logic to find `openscad.exe` on Windows assumes that its installed in one of the "Program Files" folders which doesn't allow users (like me) who run the "portable" version the ability to point this plugin to a version elsewhere on the system.

I'd like to propose updating the [Windows logic](https://github.com/kartchnb/AutoTowersGenerator/blob/main/OpenScadInterface.py#L174-L183) to first scan the `%PATH%` and then fall back to the existing behavior if the exe isn't found.

It sounds like you run on Linux so I'd be willing to attempt this change (no experience in creating Cura plugins, but you've gotta start somewhere) if you'd be willing to pull it in.

**Comment by tiimk** [comment]
You can go in to the settings of AutoTowersGenerator and manually set the OpenSCAD path to be anywhere for a portable version. 

<img width="357" alt="image" src="https://github.com/kartchnb/AutoTowersGenerator/assets/9601105/cc516ff0-7abd-4a5b-8ed8-a8791edcb3fe">

However kartchnb seems to be open to pull requests if you wanted to do the logic to scan for %PATH%.

**Comment by kleinwareio** [comment]
Ah, you're right, I just missed it and following the posted code link back does indeed show that logic is only run if the path is not already set. Thanks!

**Comment by kartchnb** [comment]
You followed the code back?  You're a brave, brave man.  So much of writing this was a learning experience and now even I am afraid to try to follow the logic...
