### ISSUE TITLE
Temperature Tower, ABA Filament?

### ISSUE THREAD

**Issue by jaseiffert** [kartchnb/AutoTowersGenerator#101]
I'm not aware of ABA Filament. Were you meaning ASA?

In the Drop Down List for the Temperature Tower. You Already have ABS so ASA is the only thing I could come up with.
And the Temperature Range seemed to fit.

Thanks,
Jeffery

**Comment by kartchnb** [comment]
I did mean "ABA".  Although I haven't used it, I understand ABA is a more UV resistant version of ABS.

**Comment by henryptung** [comment]
Given the description, this sounds a lot like ASA:

https://wiki.polymaker.com/the-basics/3d-printing-materials/asa

> ASA
> 
> Acrylonitrile Styrene Acrylate (ASA) has emerged as a superior alternative to ABS in 3D printing, combining durability with exceptional resistance to weathering. Known for its ability to **withstand UV exposure**, heat, and harsh environments, ASA is the go-to filament for functional parts that thrive outdoors. From automotive components to garden fixtures, ASA bridges the gap between industrial-grade performance and practical printability.
> 
> What Is ASA?
> 
> ASA is a thermoplastic polymer engineered to excel in outdoor and high-stress environments. Its composition—acrylonitrile for chemical resistance, styrene for rigidity, and **acrylate for UV stability**—makes it a robust alternative to ABS. **Unlike ABS, ASA retains its color and mechanical properties even after prolonged sun exposure, thanks to its UV-resistant acrylic ester elastomer.**
> 
> Key Settings
> 
> - **Nozzle Temperature: 240–280°C (start at 250°C and adjust based on filament brand).**
> 
> - Bed Temperature: 90–110°C (heated bed essential for adhesion).
> 
> - Print Speed: 35–70 mm/s (slower speeds improve layer bonding).
> 
> - Ambient Temperature: Maintain a draft-free, warm environment or use an enclosed printer (60°C chamber ideal).

This corresponds well with the current temperature tower range of 240-260°C, so I'm almost certain you're talking about ASA. For what it's worth, I've also not heard of an ABA filament material, and the [wiki page on 3D printer filaments](https://en.wikipedia.org/wiki/3D_printing_filament) lists a number of different materials including both ABS and ASA, but none with the acronym ABA.
