### ISSUE TITLE
Print direction on temp tower

### ISSUE THREAD

**Issue by ceandraka** [kartchnb/AutoTowersGenerator#103]
More  question than an issue, I hope

Thanks so much for this extension, it is really nice.

When I print the temp tower, the bridge portions print three long lines along each edge, and then short diagonal lines to fill in the center,. Bridge/tower tests in the past seem to have printed the entire first layer of each bridge with long strands. In my case, the angled first layer does not necessarily grab the three edge strands and so they get extruded into space.

Is there a recommended setting I am missing that would cause the first layer of the bridges to print lengthwise?

Thanks

**Comment by kartchnb** [comment]
Great question.  Unfortunately, I don't know of any setting that would affect that.  There's nothing inherent in the model (that I'm aware of) that would cause the slicer to prefer diagonal fill lines over long strands.  It's likely that some setting can be modified to change this behavior, but I'm not aware of what it is.
