### ISSUE TITLE
2.1.0 General remarks

### ISSUE THREAD

**Issue by 5axes** [kartchnb/AutoTowersGenerator#12]
Love this new release, adding the STL in the plugin is a good solution to speed up the tower creation operation. 

You should,  as I do check some parameters in cura to avoid some further issues Like : 
- Adaptatative Layers

- Set **on the model**  the _Remove All Holes_ depending on the line Width or the Nozzle Size

My scripts have been Updated recently due to some issue like special code present in the Header Gcode but in a commented line (G91/G90 M82/M83)  Something you should also add in your integrated Script.

Any Way good Job !

**Comment by kartchnb** [comment]
Thank you for the comments!  I can't tell you how much I appreciate you taking the time to give me advice.

I wouldn't have thought to check for "adaptive layers", but I've done that now.  

Also, I've modified all my scripts to ignore commented-out gcode by checking that the gcode instruction (G0, G91, M83, etc) are the first thing on the line. 

I don't quite understand your advice about checking for "remove all holes". I've found a setting called "meshfix_union_all_remove_holes". Is that what I'm looking for? How do I check the value for the model itself?

Thank you again for the advice! I still have a **lot** to learn, so I appreciate it.

**Comment by 5axes** [comment]
In my Plugin if the Nozzle Size is bigger than 0.4 the option Remove Holes is set on the model in order to avoid any wall thickness issue for people who want to use the Tower design with a Bigger line Width than 0.4-0.5 
![image](https://user-images.githubusercontent.com/11015345/193521730-9ba55985-efcb-4d4b-8d92-9ae3c05ff265.png)

Nozzle 0.8
![image](https://user-images.githubusercontent.com/11015345/193521795-695c3d30-04f4-4350-ae6f-ec21d9eb9be2.png)

**Comment by kartchnb** [comment]
I think that gives me everything I need.  Thank you!
