### ISSUE TITLE
Bug in Retraction type speed

### ISSUE THREAD

**Issue by DanMan32** [kartchnb/AutoTowersGenerator#14]
Not sure if this has been fixed in plugin version 2.2 but in 2.1 that is available with Cura 5.1.0 where if you select to print a retraction speed tower, it instead does a traction distance with the values intended for speed.
This creates drastic results with an Ender 3 v2 with PLA filament as too much filament is retracted/extruded too fast causing temporary jams.

I found the flaw that caused this: differences in case for the retraction type.
In RetractTowerController, you use "Speed" (capital S) to differentiate between retraction type for speed vs distance.
But in RetractTower_PostProcessing, you test type and determine if it is set to 'speed' (all lower case) and if not, default to distance.
Since because of how type is set in RetractTowerController as "Speed", the type never equals "speed" and therefore generates a distance tower.

**Comment by kartchnb** [comment]
Aurgh! That's incredibly embarrassing.

I'll get this fixed and pushed ASAP. 

THANK YOU for letting me know and for doing all the legwork for me in finding the problem!
