### ISSUE TITLE
opensCAD path

### ISSUE THREAD

**Issue by Cykelskurdk** [kartchnb/AutoTowersGenerator#19]
I just can't seem to specify the opensCAD path. i've tried and tried again. But the plugin just won't recognize that openSCAD is installed.

**Comment by kartchnb** [comment]
Well, that's unfortunate.  I thought I had OpenSCAD all figured out, but clearly not.

When you get a moment, will you give me the following information, please?
- What version of Cura you're using
- What version of OpenSCAD you have installed
- The path to your OpenSCAD installation

If you're comfortable with it, it might also help if you uploaded your cura.log file. You can find it by opening Cura's "Help" menu and selecting "Show Configuration Folder".

**Comment by kartchnb** [comment]
Never mind. I'm pretty sure this is due to an error on my part.

It **should** be fixed in version 2.3.2, which you can download here: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.3.2

Download the curpackage for your Cura version and drag and drop it onto the Cura window to install.

**Comment by ATsaruk** [comment]
Same issue, 
Cura 5.2.1 
![image](https://user-images.githubusercontent.com/55996867/200909435-cb9891ff-3b06-4ad4-af60-b1db9632ae3b.png)

[OpenSCAD](https://www.openscad.org/) version 2021.01
![image](https://user-images.githubusercontent.com/55996867/200909509-0a56daca-6aee-4c06-8b0e-5b4d1dea11b2.png)

Instalation path: C:\Program Files\OpenSCAD
![image](https://user-images.githubusercontent.com/55996867/200909558-28cd1077-6437-4379-b48a-92dd20ecc24e.png)

In Cura: Extensions\Auto Towers\Settings\OpenSCAD path set as "C:\Program Files\OpenSCAD", 
![image](https://user-images.githubusercontent.com/55996867/200909638-922a1e6a-b48a-44e2-b4d3-94247a8a3f32.png)

then press ok, and i have message: The OpenScad path "C:\Program Files\OpenSCAD" is not valid
![image](https://user-images.githubusercontent.com/55996867/200909392-8457741d-aadd-4f73-a793-b779ad928ebc.png)

**Comment by Cykelskurdk** [comment]
Mine is working after the last update

**Comment by ATsaruk** [comment]
I install it yesterday, i think it whas last version? And it doesn't work for me.

**Comment by kartchnb** [comment]
It should be fixed in the most recent version, but there's a decent chance I made a mistake somewhere. I'll take a look and get back to you when I have something to report.

Thanks, @ATsaruk.

**Comment by ComedianTF2** [comment]
If openscad is installed at the time of installing the plugin, it detects it properly and works as it should

If openscad is not installed, or installed after the plugin is installed, it gives the "The OpenScad path "C:\Program Files\OpenSCAD" is not valid" error message.

To fix it: reinstall the plugin, it will then detect openscad properly

**Comment by ATsaruk** [comment]
I try it, but it didn't help!
1. I remove plugin and close Cura
2. Run Cura, install plugin, close Cura
3. Run Cura again and go to settings, and put directory: c:\Program Files\OpenSCAD
And i recieve same issue: The OpenScad path is not valid!

**Comment by ATsaruk** [comment]
In the OpenSCAD path field, I entered C:\Program Files\OpenSCAD\openscad.exe and everything worked!

**Comment by kartchnb** [comment]
I'm glad you got it to work, @ATsaruk!  However, obviously, there are still issues with how I've implemented this and I'll need to try to figure out a more intuitive implementation.

Thanks!

**Comment by kartchnb** [comment]
I'm going to close this issue for now, since the initial problem seems to be solved.  I still feel that how the path is configured may need to be revisited, though.
