### ISSUE TITLE
Outdated version of AutoTowersGenerator on Cura Marketplace

### ISSUE THREAD

**Issue by Monteco** [kartchnb/AutoTowersGenerator#24]
![image](https://user-images.githubusercontent.com/33065620/198063199-dbf598b1-8a10-4092-b25f-ecdc8273a90a.png)

I realized that I'm using a very outdated version of AutoTowers when I compared the one on GitHub and the other on Marketplace.

On the MarketPlace it seems to be version 2.1.0 and the current one is 2.3.3 (or v8.2.0 not sure which version name I should use)

I think this is a wonderful plugin, but new users might get the wrong first impression of it if they use an outdated version.

If possible, update the MarketPlace plugin version
Thank you ^^

**Comment by kartchnb** [comment]
Thank you for the comment and the kind words!

I have actually submitted several more recent versions to the MarketPlace, but they have to go through an approval process before they show up and this sometimes takes a long time. I'm going to keep submitting updates as more and more (and more and MORE) errors are found and fixed.  Eventually, the updates will make their way to the MarketPlace.

And the version numbers ARE confusing. The latest version of my plugin (as of right now) is 2.4.1, which you can download here if you want: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.4.1.

The other version number (v8.2.0, for example), refers to the Cura API, which changes with each Cura release.  I support API versions 7.9.0 (Cura 4.13.0), 8.0.0 (Cura 5.0.0), 8.1.0 (Cura 5.1.0), and 8.2.0 (Cura 5.2.0).  If you navigate to my latest plugin and download the .curapackage with an API version that matches your version of Cura, you should be able to install it by dragging and dropping the .curapackage file onto your Cura window.

I hope that clears things up a bit.  Thank you again!
