### ISSUE TITLE
Wrong Flowtower  Script, begins whit 115%, soll 85%

### ISSUE THREAD

**Issue by Kaicura** [kartchnb/AutoTowersGenerator#29]
Wrong Flowtower  Script, begins whit 115%, must start whit  85%
Cura4.13.1 ,Win 7
![image](https://user-images.githubusercontent.com/65878296/200095122-88873ff7-15f6-42d2-a69d-8916ef8d7368.png)

**Comment by Modix3D** [comment]
Want to confirm that this issue is still there with Cura 5.2.1 and auto tower generator 2.4.0. Starts at 115 flow and ends at 85 flow

**Comment by ComedianTF2** [comment]
Want to confirm that this issue is still there with Cura 5.2.1 and auto tower generator 2.4.0. Starts at 115 flow and ends at 85 flow

**Comment by kartchnb** [comment]
Yeah... this was a stupid error on my part (aren't they all?). The script works as intended, but the model was generated with the flow labels in reverse.  This should be fixed in the next release.
