### ISSUE TITLE
Gcode extra period. Klipper Unable to parse move 'G1 F1015.2.4 ... changing speed

### ISSUE THREAD

**Issue by jaakko000** [kartchnb/AutoTowersGenerator#30]
!! Unable to parse move 'G1 **F1015.2.4** X116.392 Y122.899 E94.82338 ; AutoTowersGenerator changing speed from 42.3mm/s (2538.0mm/m) to 16.9mm/s (1015.2mm/m)'

Speed tower 20-100 stalls immediately when trying to change speed for the first time. Im guessing it has to do with the random extra period in F? 

Ender 3 V2 with newest versions of Klipper and Fluidd. 
Autotowersgenerator Version 2.4.0 and Cura 5.1.1
Cura.log, klippy.log and the offending .gcode here. Line 1017 in gcode.
https://github.com/jaakko000/Autotowersgenerror

Let me know what else you need. Works great other than this error occasionally. Thanks for the great plugin mate.

**Comment by kartchnb** [comment]
Great catch. I've written a fix, but I'm in the middle of making a bunch of other fixes and, likely, adding more issues like this one.

So, it's going to take me some time to push out an official fix. In the meantime, you can try version 2.4.3, which should fix this issue.

You can find 2.4.3 here: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.4.3

Just download the .curapackage for your version of Cura and drag and drop it onto a running Cura window to install.

Thank you for the report and all the information!
