### ISSUE TITLE
Add a Coffee button

### ISSUE THREAD

**Issue by bjoernbusch** [kartchnb/AutoTowersGenerator#38]
This plugin is the best thing since sliced bread. I was annoyed by the fixed size pre-made towers so many times, I couldn't image that this is possible. This is so much more efficient, thank you so much. I wish I was better at python and could help you with development, but maybe you could add a "buy me coffee" button somewhere, because I would like to show my gratitude somehow!

**Comment by kartchnb** [comment]
Wow! Thank you for the kind words! I wish *I* was better with Python so I made fewer mistakes.

I appreciate the kind words and the suggestion!  Also, I need to check out this "sliced bread" you speak of.

**Comment by kartchnb** [comment]
Done!
