### ISSUE TITLE
Retract Distance Tower script replaces End G-code

### ISSUE THREAD

**Issue by ZedOud** [kartchnb/AutoTowersGenerator#43]
The script for the retract tower replaces an End G-Code G1 movement, right after a G92, which causes, well...

This would tell the printer Extruder position is E1.0, whereas the previous Extrude position was E1388.91381. Then it moves the extruder to position E-1.0, thus retracting by 2mm:
```gcode
G92 E1
G1 E-1 F300
```

The retract distance script steps in and turns the above into this:
```gcode
G92 E1
G1 F300 E1388.91381
```

Spitting out the entire length of material extruded so far (minus 1mm lol).

-------

This is in Cura 5.1

My start G-Code is:
```gcode
M92 E1388.36
G28 ;Home
G1 Z15.0 F6000 ;Move the platform down 15mm
;Prime the extruder
G92 E0
G1 F200 E3
G92 E0
```

My end G-Code is:
```gcode
M104 S0
M140 S0
;Retract the filament
G92 E1
G1 E-1 F300
G28 X0 Y0
M84
```

I'm attaching g-code of a Retract Distance tower with this problem, and a Retract Speed tower that does not have this problem. (The g-code files have been renamed to *.txt because Github doesn't support uploading .gcode)
[PET retract tower 1-6mm.txt](https://github.com/kartchnb/AutoTowersGenerator/files/10146262/PET.retract.tower.1-6mm.txt)
[PETG retract speed 60-100mms.txt](https://github.com/kartchnb/AutoTowersGenerator/files/10146264/PETG.retract.speed.60-100mms.txt)

![retract distance towers](https://user-images.githubusercontent.com/7321904/205439458-481f39aa-432d-44b6-846e-fdd3dbdb8b03.jpg)

The tower closer to the viewer in the attached picture was printed with the problematic retract distance g-code I am uploading. (The second tower is a different Retract Distance going from 0.0mm to 1.4mm in 0.2mm steps.)

**Comment by kartchnb** [comment]
Ah, yes - the pesky End code.  I apologize for that.  Those pictures are... dramatic.  Thank you for the error report and uploading your gcode!  I can't tell you how much this helps.

I've made some recent updates to ensure my plugin ignore's the Start and End code, so this _should_ be fixed.  You can try it out, if you would like.  I just released version 2.5.0, which is available here: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.5.0

You should be able to install it by downloading the .curapackage file that matches the version of Cura you're using and dragging and dropping it onto a running Cura window.
