### ISSUE TITLE
Bed Level Missing settings field

### ISSUE THREAD

**Issue by 5axes** [kartchnb/AutoTowersGenerator#47]
Cura 5.2.1   Plugin release 2.5.0 

In the options for the bed level type Concentric Circle type , The field for Number of rings is missing :  
![image](https://user-images.githubusercontent.com/11015345/208391817-2f114bc9-ee17-4bae-a579-ecbe368dfea4.png)

**Comment by kartchnb** [comment]
Should be fixed in version 2.6.0 here: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.6.0

Nice catch!  As always, I appreciate the help.
