### ISSUE TITLE
Temp and Retraction towers crash printhead outside of buildplate

### ISSUE THREAD

**Issue by Edocecrous** [kartchnb/AutoTowersGenerator#52]
Hi,

I'm using an unmodified Anycubic Predator (D), and Cura 5.2.1, Linux (Xubuntu 20.04 LTS).
Manually installed the plugin from github, Cura recognizes and uses it fine, and i generated both a PLA temp tower and a retraction tower (1-6). 
Around 4.5mm high into the print (i think where the pause is), the print head goes all the way out to one side, then tries to go further down (below the build plate).
The retract tower code seemed not to have the pause in it, so that's why i tried it, but it behaved the same.
The only time i got the same behavior was when i accidentally put G-code sliced for an Ender 5 onto the Predator.

I'm guessing it might have something to do with the absolute/relative coordinates, or when the coordinate system is reset. (G92 ?)
I'm slicing  and printing with Cura just fine, only the post processed towers give me this issue.

[retraction.gcode.txt](https://github.com/kartchnb/AutoTowersGenerator/files/10395093/retraction.gcode.txt)

**Comment by kartchnb** [comment]
Thank you for letting me know.  This is a bit disturbing.

I don't understand why you have the pause in there.  That's not from my script, but another one (PauseAtHeight.py).  I wonder if there could be some interaction between the scripts.  

Thanks for the gcode - I'll take a look and see if I can figure out what's going wrong.

I appreciate the error report!

**Comment by Edocecrous** [comment]
Hi,

Please disregard the problem! I have no idea what happened, since yours was the only plugin i ever installed.
Long story short, reading what you wrote, i tried again and then searched the g-code for 'pause'. Since i couldn't find it, i risked it and run it on the printer.... and it worked, no crazy moves, the whole retract tower printed fine.

Interestingly i couldn't find a single 'thread' between the square and the round towers, not at 1 ... 6 (i printed a retract 1-6 tower)

I attach the gcode
[rettest.gcode.txt](https://github.com/kartchnb/AutoTowersGenerator/files/10418757/rettest.gcode.txt)

**Comment by kartchnb** [comment]
Well, I'm glad the printhead crash is (hopefully) not a problem.  

I'm concerned about the retraction tower because plenty of other people are saying the same thing - they don't see any difference in the different retraction settings.  Thank you for attaching the gcode again.  As far as I can tell, the gcode is correct and it *should* be using different retraction settings at each level of the tower.  But, you should, then, also be seeing different stringing at each section of the tower.

I'll keep looking into this.  Thank you!

**Comment by Edocecrous** [comment]
Ok,
If you need anything please let me know. I also printed the temp tower, and it was changing the temperature nicely and didn't give me any trouble.
I should print some basic test and set the retraction to let's say 1 in cura. My Predator has 15cm capricorn tube from extruder till top of cooling block on printhead, there should be stringing on the retract tower...

**Comment by kartchnb** [comment]
Well, I've double and triple-checked the retraction towers and even rewritten much of the code.  As far as I can see, the retraction speed and distance towers should work correctly in Release 2.6.2 (which should show up on the Marketplace soon).  Please let me know if you see an improvement.

**Comment by Edocecrous** [comment]
I'll check it out, thank you!
