### ISSUE TITLE
[Enhancement] Reduce the Plugin Menu

### ISSUE THREAD

**Issue by 5axes** [kartchnb/AutoTowersGenerator#66]
As the plugin menu is now very long you should think to a new way to reduce this list.

![image](https://user-images.githubusercontent.com/11015345/228781457-cbb4bc0e-393a-429e-ab3a-619b3b091d25.png)

Use a Drop Down List in a dedicate plugin windows ?

![image](https://user-images.githubusercontent.com/11015345/228780775-08542b0c-7777-4e16-ac49-59e7785ce1e1.png)

Keep one Menu Entry by Type of test to have the list of the different test.

**Comment by kartchnb** [comment]
Great suggestion!  Thank you!

**Comment by kartchnb** [comment]
My inexperience with QML made this a difficult update, but it should be in the next release (whenever I get around to releasing it).

Thank you again, @5axes!

**Comment by 5axes** [comment]
Nice ...  
![image](https://github.com/kartchnb/AutoTowersGenerator/assets/11015345/d9c16057-667f-4f19-a1dd-c09deddb91f2)
![image](https://github.com/kartchnb/AutoTowersGenerator/assets/11015345/ca6fd0a5-043f-41b6-9a5c-42f5dff8fea4)

Small Typo error on these labels for 

Next Version :  make it ready for translation :)
