### ISSUE TITLE
Is it automatic set the setting for each layer?

### ISSUE THREAD

**Issue by vgomasjaya** [kartchnb/AutoTowersGenerator#71]
Hello, sorry I'm a beginner...
Is this plugin automatic to set the setting?

Example:
I choose Temperature Tower, so what I must do after that? Just slice it and save it? Or I must set the temperature for each layer?

Thank you!

**Comment by kartchnb** [comment]
Good question.  Everything is automatic.  So, as you say, if you choose a Temperature Tower, you just need to slice and save it.  When you save it (or print it), the plugin automatically generates the gcode to change the temperature at each section of the tower.

I hope that makes sense.  Let me know if you have any more questions.
