### ISSUE TITLE
AutoTowersGenerator & Cura 4.X

### ISSUE THREAD

**Issue by 5axes** [kartchnb/AutoTowersGenerator#85]
Add Issue with the release 2.6.0 under Cura 4.13 Release ... For The Flow Tower got this message when I want to Potprocess the G-Code

![image](https://github.com/kartchnb/AutoTowersGenerator/assets/11015345/cb3f57b1-9368-44be-9c1b-ff5728dbc471)

**Comment by kartchnb** [comment]
Fixed.  This was a stupid error that reminds me that I'm not smart enough to write code.

But, it's fixed and checked in now.
