### ISSUE TITLE
"Custom Retraction Tower" filename too long for some printers

### ISSUE THREAD

**Issue by njefferson** [kartchnb/AutoTowersGenerator#95]
Cura Version:  5.4.0
Operating System:  Windows 11
Printer:  Flashforge Dreamer NX

Reproduction steps
Extensions-->Auto Tower-->Custom Retract Tower

This results in a filename like this: "Custom Retraction Tower - Distance 1.0-6.0x1.0"
This is too long for my printer to read.

My Anycubic Kobra Neo has no problem with it, but my older Flashforge Dreamer NX cannot open the file until I rename it to something shorter. I do not know the maximum character limit, but it works when I make it much shorter. Special characters do not seem to matter.

**Comment by kartchnb** [comment]
Another problem I didn't foresee.  It shouldn't be a problem to shorten the name.  I'll work on that for the next release.

Thank you for letting me know this is a problem.

**Comment by njefferson** [comment]
Thank you!
