### ISSUE TITLE
custom tower not generating

### ISSUE THREAD

**Issue by myrrien** [kartchnb/AutoTowersGenerator#96]
Cura 5.4.0, latest release from this repo

I see there's backslashes instead of forward slashes, maybe that's the problem?

![image](https://github.com/kartchnb/AutoTowersGenerator/assets/30466333/30bf2c96-747d-4f50-929a-456ffd51fb68)

**Comment by jenniferxgre** [comment]
I'm having the same issue also with the latest release from here and Cura 5.4.0

**Comment by kartchnb** [comment]
I believe this is an error with the "tmp" directory not always being created.  The next release will fix this.
